baseURL: https://trepix.io
languageCode: en-us
title: "Trepix"
theme: "trepix"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-111585454-1

# Enable Disqus forum
disqusShortname: blog-trepix-io

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  GitRepo: https://github.com/trepix/trepix.github.io

  # background image of the landing page
  background: "/static/images/background20.svg"

  # specify whether you want to write blog post or not
  enableBlogPost: true
  #blogURL: https://blog.trepix.io

  # some information about you
  author:
    name: "Pau Trepat"
    image: "images/avatar3.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "pau.trepat.segura@gmail.com"

    # a summary of what you do
    summary:
    - I am working on this website
    - Don't expect to much about this 😂
    - Someday I'm gonna finish it, like university
  
