baseURL: https://trepix.github.io
languageCode: en-us
title: "Trepix"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-111585454-1

# Enable Disqus forum
disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  GitRepo: https://github.com/trepix/https://trepix.github.io/
  
