version: "3"

services:
  webpack:
    image: "trepix/web-assets-builder:latest"
    volumes:
      - "./themes/trepix/:/src"
      - "/src/node_modules"
    command: start

  hugo:
    image: klakegg/hugo:0.72.0
    volumes:
      - ".:/src"
    depends_on:
      - webpack
    ports:
      - "1313:1313"
    command: server -w --disableFastRender -D
  