name: CI / CD^2
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Configure credentials
        run: |
          git config user.email "pau.trepat.segura@gmail.com"
          git config user.name "Pau Trepat Segura"

      - name: Deploy
        env:
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: make deploy
