name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Deploy
        env:
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git remote rm origin && \
          git remote add origin https://github.com/Trepix/trepix.github.io && \
          git fetch
          git config user.email "pau.trepat.segura@gmail.com"
          git config user.name "Pau Trepat Segura"
          make deploy
